import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import { Poppins } from "next/font/google";
import Navbar from "@/components/Navbar";
const poppins = Poppins({ subsets: ["latin"], weight: ['300','400','500','600','700','900']});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className}  bg-zinc-100 dark:bg-zinc-950`}>
       <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <Navbar/>
        <main className="flex-col flex w-screen justify-center content-start pt-10 md:pt-14">{children}</main>
        </ThemeProvider> 
      </body>
    </html>
  );
}
